customhost = "yeechooili-employee.cuf0jxtawdje.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "aws_user"
customdb = "yeechooiliEmp"
custombucket = "yeechooili-bucket"
customregion = "us-east-1"
